application: stage4-html
version: 1
runtime: python27
api_version: 1
threadsafe: true

#[start handlers]
handlers:
- url: /style
  static_dir: style

- url: /.*
  script: main.app
#[End handler]

#[Start librarier]
libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
#[End libraries]

